kind: Secret
apiVersion: v1
metadata:
  name: vault-test-secret
  annotations:
    avp.kubernetes.io/path: "credentials/data/deployment"
type: Opaque
data:
  username: <username> # <Vault_secret_key>
  password: <password> # <Vault_secret_key>
  apikey: <apikey> # <Vault_secret_key>
