apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack  # Ensure this matches Prometheus' `release` label
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
      - nginx-test-deployment
  endpoints:
    - port: metrics
      interval: 15s
