apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  metrics.conf: |
    server {
        listen 80;
        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
