apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9113
              name: metrics
          args:
            - /bin/sh
            - -c
            - |
              apt update && apt install -y curl && \
              /bin/bash -c "nginx -g 'daemon off;'" & \
              /bin/bash -c "while true; do sleep 3600; done"
