apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-test-deployment
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics
      port: 9113
      targetPort: metrics
