apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: http-port
      targetPort: http
    - port: 9113
      name: metrics-port
      targetPort: metrics
