apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  labels:
    release: prometheus-stack  # must match Prometheus release name
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
