apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd  # ArgoCD should be installed in this namespace
spec:
  project: default
  source:
    repoURL: https://github.com/shivamsoin/argocd.git
    targetRevision: HEAD
    path:   ./deploy-files/testing-applications/nginx-deployment    # Folder containing nginx-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
